import Image from "next/image";

/**
 * KreateUp brand marks — the genuine artwork from the DesignSeriesLog repo,
 * served from /public/brand. Nothing here is drawn or generated by hand.
 *
 * The source files are square canvases with the wordmark centred inside a wide
 * margin, so `Wordmark` crops to the type itself with an overflow window rather
 * than shrinking a mostly-empty square.
 */

export function Wordmark({ height = 28, className }: { height?: number; className?: string }) {
  return (
    <Image
      src="/brand/logo-brand.png"
      alt="KreateUp"
      width={height}
      height={height}
      priority
      className={className}
      style={{ display: "block", borderRadius: height * 0.26 }}
    />
  );
}

/** Square mark — nav rail, mobile bar, favicon source. */
export function LogoMark({ size = 36, className }: { size?: number; className?: string }) {
  return (
    <Image
      src="/brand/logo-brand.png"
      alt="KreateUp"
      width={size}
      height={size}
      priority
      className={className}
      style={{ display: "block", borderRadius: size * 0.26, objectFit: "cover" }}
    />
  );
}

/** Mark + wordmark + product name. */
export function LogoLockup({
  height = 24,
  subtitle = "DesignSeries Portal",
  className,
}: {
  height?: number;
  subtitle?: string;
  className?: string;
}) {
  return (
    <span className={`flex items-center gap-2.5 ${className ?? ""}`}>
      <LogoMark size={height + 14} />
      <span className="flex flex-col leading-none">
        <span
          className="font-bold"
          style={{ fontSize: height * 0.86, letterSpacing: "-0.03em", color: "var(--text-strong)" }}
        >
          KreateUp
        </span>
        {subtitle ? (
          <span
            className="mt-1.5 text-[9.5px] font-semibold uppercase tracking-[0.17em]"
            style={{ color: "var(--text-muted)" }}
          >
            {subtitle}
          </span>
        ) : null}
      </span>
    </span>
  );
}

/** The four-colour rule used as a cap on primary surfaces. */
export function BrandThread({ className = "" }: { className?: string }) {
  return <span aria-hidden className={`brand-thread-bar block h-[3px] w-full ${className}`} />;
}
